[project]
name = "OSN_common"
version = "0.1.0"
description = "Common scripts and functions for Slovak hospital reform OSN"

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]

[tool.black]
line-length = 120
target-version = ['py311']